llm:
  model: gpt-4o-mini

nlp:
  language: en
  region: US
  timezone: Europe/Madrid
  pre_processing: true
  intent_threshold: 0.35
  openai:
    api_key: YOUR-API-KEY

platforms:
  websocket:
    host: 0.0.0.0
    port: 8765
    streamlit:
      host: 0.0.0.0
      port: 5000
